### ISSUE TITLE
uh review? 

### ISSUE THREAD

**Issue by fourjr** [umbresp/brawlstars#1]
# client.py
- [x] `from .errors import *` - don't use wildcard imports
- [x] `self.baseUrl = 'http://brawlstars-api.herokuapp.com/api/'`  - should be self.base_url
- [x] a blank `__del__`...?
- [x] `if tag is None: raise MissingArg('tag')` - this is really useless, just don't make it an optional params and python handles it for you
- [ ] 
```py
player = Player(data) 
return player
```
i don't see the point of creating another variable here
- [x] ^^ the 2 above for get_band
- [x] get_player and get_profile should be aliases
- [x] create an `__str__`
- [x] personally think get_brawlers and get_id is redundant and get_members
- [x] classes related to the above ^^

# async client
- [x] most stuff from above
- [x] `except Exception:` - just do `except:`
- [x] do an except for JSONDecodeError as i said in sharpbit's commit comments, it's because of heroku
- [x] a LOT of unnecessary coroutines that can just be functions 

# sidenote
am kinda tired atm so this isn't comprehensive, fix all these and ill look at it again

read this https://github.com/SharpBit/abrawlpy/issues/1

I don't think invalidarg or httperror for invalid tag is a good idea, a seperate exception should be raised for that.

**Comment by umbresp** [comment]
1-3 Easy fixes.
4 How do you make it required? Just don’t specify a default value?
5-6 Legacy code, if its not a huge problem i wont touch it
7 How do you add aliases? Just create a new method with the same function but different name?
8 idk how to do that
9-10 I implemented that anticipating future endpoints. Also I like my stuff very object-oriented.
11-13 Ok 
14 Can you provide examples? I’m not sure where await is required

**Comment by fourjr** [comment]
4. Yes
5. How is it legacy code? 🤔
7. `get_player = get_profile `
8. google python str classes
14. all the class functions for profile, band, etc doesn't need to be coroutines

**Comment by umbresp** [comment]
4 k
5-6 from my other wrapper cocasync
7 give example in context pls
8 k
14 but then they wont be asynchronous

**Comment by fourjr** [comment]
what's the use for it to be asynchronous? those functions don't take up a lot of runtime and even if you call it "asyncly", it won't have much of an effect

**Comment by fourjr** [comment]
ctrl+f `__str__`
http://www.greenteapress.com/thinkpython/html/book018.html

**Comment by umbresp** [comment]
Ok I did most of them. 

Stuff I am still confused about:
- How to make method aliases

Stuff I didn't do
- async client is supposed to be purely async, if they don't want async, they can just use the regular client
- get_id, get_members, etc all return objects and i think it looks better that way
- fix baseUrl to base_url because I can't find all the places where I used it and also nobody will want to get the base url so there's no point and its immutable anyways

**Comment by SharpBit** [comment]
1. method aliases: `get_player = alias`, or if in `__init__`, add `self` to both
2. idk what u and 4jr mean
3. idk ask 4jr he seems to think they are very unnecessary
4. use `ctrl shift f` in sublime text for that (find `self.baseUrl` in `all open files and folders` (default) and replace with `self.base_url`) and 4jr wants u to be in the habit of following pep8

**Comment by umbresp** [comment]
1. I still dont know what you mean
2. this is about asyncing and not asyncing
3. i just did
4. too lazy also all other attributes are camelCase cuz i didn't use camel killer box so this is for uniformity

**Comment by SharpBit** [comment]
1. after your `get_player` function, put this:
```py
get_player = get_profile
```
2. k
3. k
4. 4jr wants u to follow pep8 (he says it's more important than anything else, i think, except maybe copying code) and also, ctrl shift f is way easier then searching through yourself and fixing each one, so idk why you say "too lazy"

**Comment by umbresp** [comment]
1. like this?
```py
def get_player(self, tag):

        tag = tag.strip("#")
        tag = tag.upper()

        try:
            with self.session as session:
                resp = sesssion.get(f'{self.baseUrl}players/{tag}', headers=self.headers, timeout=self.timeout)
            if resp.status_code == 200:
                data = resp.json()
            elif 500 > resp.status_code > 400:
                raise HTTPError(resp.status_code)
            else:
                raise Error()
        except ValueError:
            raise MissingData('data')
        except:
            raise Timeout()


        data = Box(data)
        player = Player(data)
        return player
    get_player = get_profile
```
2. k
3. k
4. k

**Comment by SharpBit** [comment]
1. no, remove 4 spaces from the `get_player = get_profile`. It should be outside the function itself
4. um so yes or no?

**Comment by umbresp** [comment]
1. it is unindented, the first line just got its indent removed
2. idk it would be weird for everything else to be camelCase and just that to be snake_case. example:

Attributes
player.base_url
player.trophies
player.highestTrophies
player.showdownVictories

Methods
player.get_band()
player.get_id()

It would feel weird to me if only one of the attributes were snake case while everything else was camel case because that was how i was differentiating between methods and variables

**Comment by SharpBit** [comment]
1. ok
2. the player class doesn't have that attribute... it's the client and async client

**Comment by umbresp** [comment]
oh sorry but u can say the same for client too, even though client doesn't have any important attributes it would be weird for all other attributes to be camelCase except that one attribute of client.

**Comment by SharpBit** [comment]
idk how it's weird, it's pep8 m8

**Comment by umbresp** [comment]
the only way i would switch it is if i used camel killer box for everything else but i dont want to because then ill be copying u since i dont know how to use it

also are u sure its `get_player = get_profile` and not `get_profile = get_player`

**Comment by SharpBit** [comment]
1. idk why you want it to be camelcase so much
2. oops yea switch it i made that same mistake on mine too

**Comment by umbresp** [comment]
1. i dont want it to be camelcase so much. i want them all to be either snake case or camel case, and they were all camel case until now

**Comment by SharpBit** [comment]
@fourjr please help me convince this man to follow pep8 kthx

**Comment by umbresp** [comment]
AEUORINAEIORNBON%(WN#%VASODI its the fucking api and ill probably keep them camel case unless u teach me how to use camel killer box

**Comment by SharpBit** [comment]
AEUORINAEIORNBON%(WN#%VASODI `Class_That_Inherits_Box(data, camel_killer_box=True)`
or just follow pep8 m8 so u don't have to change ur docs from camelCase to snake_case and ONLY one attribute instead of all. 🤷‍♂️

**Comment by umbresp** [comment]
what if the class doesn't inherit box

**Comment by SharpBit** [comment]
i thought all your classes inherit box

**Comment by umbresp** [comment]
not client and asyncclient

**Comment by umbresp** [comment]
could i make them inherit from box tho?

**Comment by SharpBit** [comment]
you don't need client to inherit from box

**Comment by umbresp** [comment]
but i want to camel_kill client and asyncclient

**Comment by SharpBit** [comment]
um client doesn't have any attributes that the user needs, only methods, so it doesn't matter

**Comment by umbresp** [comment]
then why does baseUrl need to be base_url its not like the user is going to use it anyways cuz its always the same thing

**Comment by SharpBit** [comment]
please stop replying to me

**Comment by fourjr** [comment]
because people read source and it looks ugly

**Comment by umbresp** [comment]
hey but on the bright side everything else is fixed right?

**Comment by umbresp** [comment]
also i still dont understand the aliasing thing

**Comment by fourjr** [comment]
alias is because some people call it player and some call it profile

**Comment by umbresp** [comment]
no i know but how do i implement it

**Comment by fourjr** [comment]
`self.get_player = self.get_profile ` in init

**Comment by fourjr** [comment]
in `__init__.py` you should import * errors

**Comment by umbresp** [comment]
u sure its not the other way around for get_profile

**Comment by fourjr** [comment]
idk do what your program does :/

you get the concept right?

**Comment by umbresp** [comment]
ok i changed all that

**Comment by fourjr** [comment]
does session.close not work?

**Comment by umbresp** [comment]
I ctrl f ed on the requests documentation for close() but nothing showed up so I assumed it didn't exist

also for aliasing do i have to await the coroutines (e.g. self.get_player = await self.get_profile)

**Comment by fourjr** [comment]
lmao i just evalled `dir(requests.Session()) `

**Comment by fourjr** [comment]
nope don't await

**Comment by umbresp** [comment]
ok

**Comment by SharpBit** [comment]
You still didn't do everything? :/

**Comment by umbresp** [comment]
uh whats there left to do

**Comment by 0arm** [comment]
Ahahaha I'm reading through this and I can see that umbresp is actually fucking retarded. Why make this library if you don't know how to use python?

**Comment by SharpBit** [comment]
@4rqm it's because he wanted to 
1. Steal the brawlstars name
2. Make a better one than mine
